version: '3'

services:
  streamlink-recorder:
    build:
      context: .
    volumes:
      - ./download:/home/download
    environment:
      - streamLink=https://www.twitch.tv/tumblurr
      - streamQuality=360p
      - streamName=theprimeagen-recording
      - streamOptions=--twitch-disable-reruns
      - uid=1000
      - gid=1000
