version: '3'

services:
  streamlink-recorder:
    build:
      context: .
    volumes:
      - ./download:/home/download
    environment:
      - streamLink=${STREAM_LINK:?err}
      - streamQuality=${STREAM_QUALITY:-360p}
      - streamName=${STREAM_NAME:?err}
      - streamOptions=${STREAM_OPTIONS:---twitch-disable-reruns}
      - uid=${UID:-1000}
      - gid=${GID:-1000}
