version: '3'

services:
  streamlink-recorder:
    build:
      context: .
    volumes:
      - ./download:/home/download
    environment:
      - STREAM_LINK=${STREAM_LINK:?err}
      - STREAM_QUALITY=${STREAM_QUALITY:-360p}
      - STREAM_NAME=${STREAM_NAME:?err}
      - STREAM_OPTIONS=${STREAM_OPTIONS:---twitch-disable-reruns}
      - uid=${UID:-1000}
      - gid=${GID:-1000}
